#!/bin/bash
#incremental Backup
#Variables for the name of the file
destination="$1" #Das erste Argument welches dem Script übergeben wird
day=$(date +%Y-%m-%d) #date
sunday=$(date +%A) #gets the Day.
hostname=$(hostname -s) #returns ubuntu
backup_files="/home/cyrill" #first argument

echo "$day"
error() {
  printf '\E[31m'; echo "$@"; printf 'E[0m'
}
#Throw error if Script is not run as Root
if  [[ ! $EUID -eq 0 ]]; then
  error "this script should be run as root user"
  exit 1
fi

if [ ! -d "/sys/bus/usb/devices/1-1" ]; then #check if usb drive is plugged in
  error "Please plug in USB drive"
  exit 1
fi

if [ ! -d "$destination" ]; then #check if provided path does not exists
  error " "$destination" does not exist. Please provide a valid directory"
  exit 1
fi

#checks if there is already a full backup in the folder $destination and today is not sunday
if [ "$(find "$destination" -mindepth 1 -print -quit 2>/dev/null)" ] && [ ! "${day}" = "Sunday" ]; then

    echo "Not empty, do incremental backup"
     #change the name of the archive file
     archive_file="Incremental_$hostname-$day.tar.gz"

     #Most important part of the script:
     tar --create \
            --file=$destination/$archive_file \
            --listed-incremental=/var/log/timestamp \
            $backup_files

    #rm -R timestamp #make a new timestamp, delete the old timestamp
    #touch timestamp #Reference time for incremental backup. This is very important-
    echo "Backup finished. Saving to USB stick. . ."

else
  #Full Backup

    archive_file="$hostname-$day.tar.gz"
    echo "$destination is empty. This means I backup all the files"
    read -p "Press [Enter] key to start backup..."
    echo "Backing up $backup_files to $destination/$archive_file"
    # Backup The Files using tar.
    tar --create \
           --file=$destination/$archive_file \
           --listed-incremental=/var/log/timestamp \
           $backup_files

    #rm -R timestamp
    #touch timestamp #Reference time for incremental backup. This is very important-
    echo "Backup finished. Saving to USB stick. . ."
fi

#Usb Drive mounten falls nicht schon gemacht
#mount /dev/sdd1 /mnt
#Finally, copy backup archive to USB drive
#cp -R /backup /mnt
echo "finished copying to USB drive"
